services:
  db:
    image: postgres:15
    container_name: library-db
    restart: unless-stopped
    environment:
      # Credenciales internas de Postgres (coinciden con tu DATABASE_URL de Docker)
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library-net

  api:
    build: .
    container_name: library-api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env  # Carga JWT_SECRET, LOG_LEVEL y el DATABASE_URL original para ejecuci√≥n fuera de Docker
    environment:
      # Dentro de Docker, la API debe conectar al servicio "db", no a localhost
      DATABASE_URL: postgresql://library_user:library_pass@db:5432/library_db
    ports:
      - "8000:8000"
    networks:
      - library-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: library-pgadmin
    restart: unless-stopped
    environment:
      # Puedes cambiarlos si quieres, no afectan a la API
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - library-net

volumes:
  db_data:

networks:
  library-net:
    driver: bridge
